/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadernoRouteImport } from './routes/caderno'
import { Route as LivroRouteImport } from './routes/livro'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as ProjetoRouteImport } from './routes/projeto'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as LivroIndexRouteImport } from './routes/livro.index'
import { Route as LivroSlugRouteImport } from './routes/livro.$slug'
import { Route as SemanaIndexRouteImport } from './routes/semana.index'
import { Route as SemanaIdRouteImport } from './routes/semana.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadernoRoute = CadernoRouteImport.update({
  id: '/caderno',
  path: '/caderno',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroRoute = LivroRouteImport.update({
  id: '/livro',
  path: '/livro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoRoute = ProjetoRouteImport.update({
  id: '/projeto',
  path: '/projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const LivroIndexRoute = LivroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LivroRoute,
} as any)
const LivroSlugRoute = LivroSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LivroRoute,
} as any)
const SemanaIndexRoute = SemanaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SemanaRoute,
} as any)
const SemanaIdRoute = SemanaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SemanaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caderno': typeof CadernoRoute
  '/livro': typeof LivroRouteWithChildren
  '/progresso': typeof ProgressoRoute
  '/projeto': typeof ProjetoRoute
  '/semana': typeof SemanaRouteWithChildren
  '/vault': typeof VaultRoute
  '/livro/$slug': typeof LivroSlugRoute
  '/semana/$id': typeof SemanaIdRoute
  '/livro/': typeof LivroIndexRoute
  '/semana/': typeof SemanaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caderno': typeof CadernoRoute
  '/progresso': typeof ProgressoRoute
  '/projeto': typeof ProjetoRoute
  '/vault': typeof VaultRoute
  '/livro/$slug': typeof LivroSlugRoute
  '/semana/$id': typeof SemanaIdRoute
  '/livro': typeof LivroIndexRoute
  '/semana': typeof SemanaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caderno': typeof CadernoRoute
  '/livro': typeof LivroRouteWithChildren
  '/progresso': typeof ProgressoRoute
  '/projeto': typeof ProjetoRoute
  '/semana': typeof SemanaRouteWithChildren
  '/vault': typeof VaultRoute
  '/livro/$slug': typeof LivroSlugRoute
  '/semana/$id': typeof SemanaIdRoute
  '/livro/': typeof LivroIndexRoute
  '/semana/': typeof SemanaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caderno'
    | '/livro'
    | '/progresso'
    | '/projeto'
    | '/semana'
    | '/vault'
    | '/livro/$slug'
    | '/semana/$id'
    | '/livro/'
    | '/semana/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caderno'
    | '/progresso'
    | '/projeto'
    | '/vault'
    | '/livro/$slug'
    | '/semana/$id'
    | '/livro'
    | '/semana'
  id:
    | '__root__'
    | '/'
    | '/caderno'
    | '/livro'
    | '/progresso'
    | '/projeto'
    | '/semana'
    | '/vault'
    | '/livro/$slug'
    | '/semana/$id'
    | '/livro/'
    | '/semana/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadernoRoute: typeof CadernoRoute
  LivroRoute: typeof LivroRouteWithChildren
  ProgressoRoute: typeof ProgressoRoute
  ProjetoRoute: typeof ProjetoRoute
  SemanaRoute: typeof SemanaRouteWithChildren
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caderno': {
      id: '/caderno'
      path: '/caderno'
      fullPath: '/caderno'
      preLoaderRoute: typeof CadernoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro': {
      id: '/livro'
      path: '/livro'
      fullPath: '/livro'
      preLoaderRoute: typeof LivroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto': {
      id: '/projeto'
      path: '/projeto'
      fullPath: '/projeto'
      preLoaderRoute: typeof ProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livro/': {
      id: '/livro/'
      path: '/'
      fullPath: '/livro/'
      preLoaderRoute: typeof LivroIndexRouteImport
      parentRoute: typeof LivroRoute
    }
    '/livro/$slug': {
      id: '/livro/$slug'
      path: '/$slug'
      fullPath: '/livro/$slug'
      preLoaderRoute: typeof LivroSlugRouteImport
      parentRoute: typeof LivroRoute
    }
    '/semana/': {
      id: '/semana/'
      path: '/'
      fullPath: '/semana/'
      preLoaderRoute: typeof SemanaIndexRouteImport
      parentRoute: typeof SemanaRoute
    }
    '/semana/$id': {
      id: '/semana/$id'
      path: '/$id'
      fullPath: '/semana/$id'
      preLoaderRoute: typeof SemanaIdRouteImport
      parentRoute: typeof SemanaRoute
    }
  }
}

interface LivroRouteChildren {
  LivroSlugRoute: typeof LivroSlugRoute
  LivroIndexRoute: typeof LivroIndexRoute
}

const LivroRouteChildren: LivroRouteChildren = {
  LivroSlugRoute: LivroSlugRoute,
  LivroIndexRoute: LivroIndexRoute,
}

const LivroRouteWithChildren = LivroRoute._addFileChildren(LivroRouteChildren)

interface SemanaRouteChildren {
  SemanaIdRoute: typeof SemanaIdRoute
  SemanaIndexRoute: typeof SemanaIndexRoute
}

const SemanaRouteChildren: SemanaRouteChildren = {
  SemanaIdRoute: SemanaIdRoute,
  SemanaIndexRoute: SemanaIndexRoute,
}

const SemanaRouteWithChildren =
  SemanaRoute._addFileChildren(SemanaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadernoRoute: CadernoRoute,
  LivroRoute: LivroRouteWithChildren,
  ProgressoRoute: ProgressoRoute,
  ProjetoRoute: ProjetoRoute,
  SemanaRoute: SemanaRouteWithChildren,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
